"""add_blog_app_models

Revision ID: ba49484a9a0d
Revises: 9cee985b3695
Create Date: 2025-07-31 12:02:32.631511

Business Context:
- TODO: Describe the business reason for this migration
- TODO: List any data impact or requirements
- TODO: Note any rollback considerations

Technical Notes:
- TODO: Describe any complex changes or constraints
- TODO: Note any performance implications
- TODO: Document any manual steps required

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ba49484a9a0d'
down_revision = '9cee985b3695'
branch_labels = None
depends_on = None


def upgrade():
    """Apply migration changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    """Rollback migration changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
