"""add_blog_post_tag_association_table

Revision ID: c71ff493a874
Revises: ba49484a9a0d
Create Date: 2025-07-31 12:16:56.928741

Business Context:
- TODO: Describe the business reason for this migration
- TODO: List any data impact or requirements
- TODO: Note any rollback considerations

Technical Notes:
- TODO: Describe any complex changes or constraints
- TODO: Note any performance implications
- TODO: Document any manual steps required

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c71ff493a874'
down_revision = 'ba49484a9a0d'
branch_labels = None
depends_on = None


def upgrade():
    """Apply migration changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_blog_post_category_id'), 'blog_post', ['category_id'], unique=False)
    op.create_index('ix_post_author_status', 'blog_post', ['author_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    """Rollback migration changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_author_status', table_name='blog_post')
    op.drop_index(op.f('ix_blog_post_category_id'), table_name='blog_post')
    # ### end Alembic commands ###
